spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1:3306/statistics?characterEncoding=utf-8&useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone:
      GMT+8
mybatis:
  type-aliases-package: com.dyz.entity
  mapper-locations: classpath:mapper/*.xml
server: 
  servlet: 
    context-path: /sta
  tomcat:
    uri-encoding: UTF-8
    
